version: '3.7'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      dev_network:
        aliases:
          - dev-adminer
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'phong2305'
      MYSQL_USER: 'phong2305'
      MYSQL_PASS: '123456'
    volumes:
      - data-volume:/var/lib/mysql
    networks:
      dev_network:
        aliases:
          - dev-mysql
volumes:
  data-volume:
networks:
  dev_network:
    name: "dev_network"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16